[workspace]
members = [
  "crates/beehive",
  "crates/cli",
  "crates/core",
  "crates/crypto",
  "crates/dns",
  "crates/gateway",
  "crates/gateway-engine",
  "crates/gateway-tonic",
  "crates/gateway-tower",
  "crates/library-tonic",
  "crates/mqtt",
  "crates/station",
  "crates/store",
  "crates/web",
]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
base32 = "0.5.1"
bytes = "1.7.2"
clap = "4.5.19"
color-eyre = "0.6.3"
derive_more = "1.0.0"
flume = "0.11.0"
futures = "0.3.31"
hyper = "1.4.1"
lararium = { path = "crates/core" }
lararium-crypto = { path = "crates/crypto" }
lararium-dns = { path = "crates/dns" }
lararium-gateway-engine = { path = "crates/gateway-engine" }
lararium-gateway-tonic = { path = "crates/gateway-tonic" }
lararium-gateway-tower = { path = "crates/gateway-tower" }
lararium-library-tonic = { path = "crates/library-tonic" }
lararium-mqtt = { path = "crates/mqtt" }
lararium-store = { path = "crates/store" }
mdns-sd = "0.11.5"
openssl = "0.10.66"
prost = "0.13.3"
rumqttc = "0.24.0"
serde = "1.0.210"
serde_json = "1.0.128"
serialport = "4.5.1"
sqlx = "0.8.2"
strum = "0.26.3"
tokio = "1.40.0"
tokio-stream = "0.1.16"
tonic = "0.12.3"
tonic-build = "0.12.3"
tower = "0.5.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = "1.10.0"

[workspace.lints.clippy]
cargo = "warn"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
strip = true
