[workspace]
members = [
  "crates/api",
  "crates/beehive",
  "crates/cli",
  "crates/core",
  "crates/crypto",
  "crates/curator",
  "crates/dhcp",
  "crates/dns",
  "crates/gateway",
  "crates/mqtt",
  "crates/rules",
  "crates/station",
  "crates/store",
]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
axum = "0.7.7"
base32 = "0.5.1"
bincode = "1.3.3"
bytes = "1.8.0"
clap = "4.5.20"
color-eyre = "0.6.3"
derive_more = "1.0.0"
flume = "0.11.1"
futures = "0.3.31"
gstreamer = "0.23.3"
gstreamer-app = "0.23.3"
gstreamer-audio = "0.23.2"
gstreamer-video = "0.23.3"
hyper = "1.5.0"
lararium-api = { path = "crates/api" }
lararium-core = { path = "crates/core" }
lararium-crypto = { path = "crates/crypto" }
lararium-dhcp = { path = "crates/dhcp" }
lararium-dns = { path = "crates/dns" }
lararium-mqtt = { path = "crates/mqtt" }
lararium-store = { path = "crates/store" }
openssl = "0.10.68"
reqwest = "0.12.9"
serde = "1.0.214"
serde_json = "1.0.132"
serialport = "4.6.0"
sqlx = "0.8.2"
strum = "0.26.3"
tokio = "1.41.1"
tokio-stream = "0.1.16"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = "1.11.0"
wasmtime = "26.0.1"

[workspace.lints.clippy]
cargo = "warn"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
strip = true
