[package]
name = "lararium-abi"
edition = "2021"
publish = false
version.workspace = true

[dependencies]
ciborium = { workspace = true }
lararium = { workspace = true }
serde = { workspace = true }

[features]

[lints]
workspace = true
