[package]
name = "cli"
edition = "2021"
publish = false
version.workspace = true

[dependencies]
api = { workspace = true, features = ["client"] }
clap = { workspace = true, features = ["derive", "env"] }
color-eyre = { workspace = true }

[lints]
workspace = true
