[package]
name = "lararium-rules"
edition = "2021"
publish = false
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
lararium-core = { workspace = true }

[features]

[lints]
workspace = true
