[package]
name = "lararium-mqtt"
edition = "2021"
publish = false
version.workspace = true

[dependencies]
derive_more = { workspace = true, features = ["from"] }

[features]
default = []
client = []
server = []

[lints]
workspace = true
