[package]
name = "lararium-gateway-tonic"
edition = "2021"
version.workspace = true

[dependencies]
lararium-gateway-engine = { workspace = true }
lararium = { workspace = true, features = ["proto"] }
tonic = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
