package modules:extension;

world extension {
    record create-container-args {
        name: string,
        root-dir: string,
        work-dir: string,
        command: string,
        args: list<string>,
        env: list<tuple<string, string>>,
        wayland: bool,
    }

    import download-image: func(reference: string, path: string) -> result<_, string>;

    import create-container: func(args: create-container-args) -> result<_, string>;
    import run-container: func(name: string) -> result<_, string>;
    import kill-container: func(name: string) -> result<_, string>;

    import mount-local-volume: func(path: string, name: string) -> result<_, string>;
    import mount-shared-volume: func(path: string, name: string) -> result<_, string>;
    import mount-temporary-volume: func(path: string) -> result<_, string>;

    export run: func() -> result<_, string>;
}
