package modules:extension;

interface oci {
    download-image: func(reference: string);
    run-container: func();
}

world extension {
    import oci;

    export run: func() -> result<_, string>;
}
