package modules:extension;

world extension {
    record create-container-args {
        name: string,
        root-dir: string,
        work-dir: string,
        command: string,
        args: list<string>,
        env: list<tuple<string, string>>,
        wayland: bool,
        pipewire: bool,
    }

    record partition {
        major: u32,
        minor: u32,
        blocks: u64,
        name: string,
    }

    import download-image: func(reference: string, destination: string);
    import create-container: func(args: create-container-args) -> result<_, string>;
    import run-container: func(name: string);
    import kill-container: func(name: string);

    import list-partitions: func() -> result<list<partition>, string>;

    export run: func() -> result<_, string>;
}
