[package]
name = "lararium"
edition = "2021"
publish = false
version.workspace = true

[dependencies]
derive_more = { workspace = true, features = ["from", "into"] }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
