use super::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EmberStatus {
    Success,
    ErrFatal,
    BadArgument,
    EepromMfgStackVersionMismatch,
    EepromMfgVersionMismatch,
    EepromStackVersionMismatch,
    NoBuffers,
    SerialInvalidBaudRate,
    SerialInvalidPort,
    SerialTxOverflow,
    SerialRxOverflow,
    SerialRxFrameError,
    SerialRxParityError,
    SerialRxEmpty,
    SerialRxOverrunError,
    MacNoData,
    MacJoinedNetwork,
    MacBadScanDuration,
    MacIncorrectScanType,
    MacInvalidChannelMask,
    MacCommandTransmitFailure,
    MacTransmitQueueFull,
    MacUnknownHeaderType,
    MacScanning,
    MacNoAckReceived,
    MacIndirectTimeout,
    SimEepromErasePageGreen,
    SimEepromErasePageRed,
    SimEepromFull,
    ErrFlashWriteInhibited,
    ErrFlashVerifyFailed,
    SimEepromInit1Failed,
    SimEepromInit2Failed,
    SimEepromInit3Failed,
    ErrFlashProgFail,
    ErrFlashEraseFail,
    ErrBootloaderTrapTableBad,
    ErrBootloaderTrapUnknown,
    ErrBootloaderNoImage,
    DeliveryFailed,
    BindingIndexOutOfRange,
    AddressTableIndexOutOfRange,
    InvalidBindingIndex,
    InvalidCall,
    CostNotKnown,
    MaxMessageLimitReached,
    MessageTooLong,
    BindingIsActive,
    AddressTableEntryIsActive,
    AdcConversionDone,
    AdcConversionBusy,
    AdcConversionDeferred,
    AdcNoConversionPending,
    SleepInterrupted,
    PhyTxUnderflow,
    PhyTxIncomplete,
    PhyInvalidChannel,
    PhyInvalidPower,
    PhyTxBusy,
    PhyTxCcaFail,
    PhyOscillatorCheckFailed,
    PhyAckReceived,
    NetworkUp,
    NetworkDown,
    JoinFailed,
    MoveFailed,
    CannotJoinAsRouter,
    NodeIdChanged,
    PanIdChanged,
    NetworkOpened,
    NetworkClosed,
    NotJoined,
    InvalidSecurityLevel,
    NetworkBusy,
    InvalidEndpoint,
    BindingHasChanged,
    InsufficientRandomData,
    ApsEncryptionError,
    SecurityStateNotSet,
    SourceRouteFailure,
    ManyToOneRouteFailure,
    NoBeacons,
    ReceivedKeyInTheClear,
    NoNetworkKeyReceived,
    NoLinkKeyReceived,
    PreconfiguredKeyRequired,
    StackAndHardwareMismatch,
    IndexOutOfRange,
    KeyTableInvalidAddress,
    TableFull,
    LibraryNotPresent,
    TableEntryErased,
    SecurityConfigurationInvalid,
    TooSoonForSwitchKey,
    OperationInProgress,
    KeyNotAuthorized,
    SecurityDataInvalid,
    ApplicationError0,
    ApplicationError1,
    ApplicationError2,
    ApplicationError3,
    ApplicationError4,
    ApplicationError5,
    ApplicationError6,
    ApplicationError7,
    ApplicationError8,
    ApplicationError9,
    ApplicationError10,
    ApplicationError11,
    ApplicationError12,
    ApplicationError13,
    ApplicationError14,
    ApplicationError15,
}

impl Decode for EmberStatus {
    fn try_decode_from<B: Buf>(buffer: &mut B) -> Result<Self, DecodeError> {
        if buffer.remaining() < 1 {
            return Err(DecodeError::InsufficientData);
        }
        use EmberStatus::*;
        Ok(match buffer.get_u8() {
            0x00 => Success,
            0x01 => ErrFatal,
            0x02 => BadArgument,
            0x04 => EepromMfgStackVersionMismatch,
            0x06 => EepromMfgVersionMismatch,
            0x07 => EepromStackVersionMismatch,
            0x18 => NoBuffers,
            0x20 => SerialInvalidBaudRate,
            0x21 => SerialInvalidPort,
            0x22 => SerialTxOverflow,
            0x23 => SerialRxOverflow,
            0x24 => SerialRxFrameError,
            0x25 => SerialRxParityError,
            0x26 => SerialRxEmpty,
            0x27 => SerialRxOverrunError,
            0x31 => MacNoData,
            0x32 => MacJoinedNetwork,
            0x33 => MacBadScanDuration,
            0x34 => MacIncorrectScanType,
            0x35 => MacInvalidChannelMask,
            0x36 => MacCommandTransmitFailure,
            0x39 => MacTransmitQueueFull,
            0x3A => MacUnknownHeaderType,
            0x3D => MacScanning,
            0x40 => MacNoAckReceived,
            0x42 => MacIndirectTimeout,
            0x43 => SimEepromErasePageGreen,
            0x44 => SimEepromErasePageRed,
            0x45 => SimEepromFull,
            0x46 => ErrFlashWriteInhibited,
            0x47 => ErrFlashVerifyFailed,
            0x48 => SimEepromInit1Failed,
            0x49 => SimEepromInit2Failed,
            0x4A => SimEepromInit3Failed,
            0x4B => ErrFlashProgFail,
            0x4C => ErrFlashEraseFail,
            0x58 => ErrBootloaderTrapTableBad,
            0x59 => ErrBootloaderTrapUnknown,
            0x5A => ErrBootloaderNoImage,
            0x66 => DeliveryFailed,
            0x69 => BindingIndexOutOfRange,
            0x6A => AddressTableIndexOutOfRange,
            0x6C => InvalidBindingIndex,
            0x70 => InvalidCall,
            0x71 => CostNotKnown,
            0x72 => MaxMessageLimitReached,
            0x74 => MessageTooLong,
            0x75 => BindingIsActive,
            0x76 => AddressTableEntryIsActive,
            0x80 => AdcConversionDone,
            0x81 => AdcConversionBusy,
            0x82 => AdcConversionDeferred,
            0x84 => AdcNoConversionPending,
            0x85 => SleepInterrupted,
            0x88 => PhyTxUnderflow,
            0x89 => PhyTxIncomplete,
            0x8A => PhyInvalidChannel,
            0x8B => PhyInvalidPower,
            0x8C => PhyTxBusy,
            0x8D => PhyTxCcaFail,
            0x8E => PhyOscillatorCheckFailed,
            0x8F => PhyAckReceived,
            0x90 => NetworkUp,
            0x91 => NetworkDown,
            0x94 => JoinFailed,
            0x96 => MoveFailed,
            0x98 => CannotJoinAsRouter,
            0x99 => NodeIdChanged,
            0x9A => PanIdChanged,
            0x9C => NetworkOpened,
            0x9D => NetworkClosed,
            0x93 => NotJoined,
            0x95 => InvalidSecurityLevel,
            0xA1 => NetworkBusy,
            0xA3 => InvalidEndpoint,
            0xA4 => BindingHasChanged,
            0xA5 => InsufficientRandomData,
            0xA6 => ApsEncryptionError,
            0xA8 => SecurityStateNotSet,
            0xA9 => SourceRouteFailure,
            0xAA => ManyToOneRouteFailure,
            0xAB => NoBeacons,
            0xAC => ReceivedKeyInTheClear,
            0xAD => NoNetworkKeyReceived,
            0xAE => NoLinkKeyReceived,
            0xAF => PreconfiguredKeyRequired,
            0xB0 => StackAndHardwareMismatch,
            0xB1 => IndexOutOfRange,
            0xB3 => KeyTableInvalidAddress,
            0xB4 => TableFull,
            0xB5 => LibraryNotPresent,
            0xB6 => TableEntryErased,
            0xB7 => SecurityConfigurationInvalid,
            0xB8 => TooSoonForSwitchKey,
            0xBA => OperationInProgress,
            0xBB => KeyNotAuthorized,
            0xBD => SecurityDataInvalid,
            0xF0 => ApplicationError0,
            0xF1 => ApplicationError1,
            0xF2 => ApplicationError2,
            0xF3 => ApplicationError3,
            0xF4 => ApplicationError4,
            0xF5 => ApplicationError5,
            0xF6 => ApplicationError6,
            0xF7 => ApplicationError7,
            0xF8 => ApplicationError8,
            0xF9 => ApplicationError9,
            0xFA => ApplicationError10,
            0xFB => ApplicationError11,
            0xFC => ApplicationError12,
            0xFD => ApplicationError13,
            0xFE => ApplicationError14,
            0xFF => ApplicationError15,
            code => return Err(DecodeError::Invalid),
        })
    }
}

impl Encode for EmberStatus {
    fn encode_to<B: BufMut>(
        &self,
        buffer: &mut B,
    ) {
        use EmberStatus::*;
        let byte = match self {
            Success => 0x00,
            ErrFatal => 0x01,
            BadArgument => 0x02,
            EepromMfgStackVersionMismatch => 0x04,
            EepromMfgVersionMismatch => 0x06,
            EepromStackVersionMismatch => 0x07,
            NoBuffers => 0x18,
            SerialInvalidBaudRate => 0x20,
            SerialInvalidPort => 0x21,
            SerialTxOverflow => 0x22,
            SerialRxOverflow => 0x23,
            SerialRxFrameError => 0x24,
            SerialRxParityError => 0x25,
            SerialRxEmpty => 0x26,
            SerialRxOverrunError => 0x27,
            MacNoData => 0x31,
            MacJoinedNetwork => 0x32,
            MacBadScanDuration => 0x33,
            MacIncorrectScanType => 0x34,
            MacInvalidChannelMask => 0x35,
            MacCommandTransmitFailure => 0x36,
            MacTransmitQueueFull => 0x39,
            MacUnknownHeaderType => 0x3A,
            MacScanning => 0x3D,
            MacNoAckReceived => 0x40,
            MacIndirectTimeout => 0x42,
            SimEepromErasePageGreen => 0x43,
            SimEepromErasePageRed => 0x44,
            SimEepromFull => 0x45,
            ErrFlashWriteInhibited => 0x46,
            ErrFlashVerifyFailed => 0x47,
            SimEepromInit1Failed => 0x48,
            SimEepromInit2Failed => 0x49,
            SimEepromInit3Failed => 0x4A,
            ErrFlashProgFail => 0x4B,
            ErrFlashEraseFail => 0x4C,
            ErrBootloaderTrapTableBad => 0x58,
            ErrBootloaderTrapUnknown => 0x59,
            ErrBootloaderNoImage => 0x5A,
            DeliveryFailed => 0x66,
            BindingIndexOutOfRange => 0x69,
            AddressTableIndexOutOfRange => 0x6A,
            InvalidBindingIndex => 0x6C,
            InvalidCall => 0x70,
            CostNotKnown => 0x71,
            MaxMessageLimitReached => 0x72,
            MessageTooLong => 0x74,
            BindingIsActive => 0x75,
            AddressTableEntryIsActive => 0x76,
            AdcConversionDone => 0x80,
            AdcConversionBusy => 0x81,
            AdcConversionDeferred => 0x82,
            AdcNoConversionPending => 0x84,
            SleepInterrupted => 0x85,
            PhyTxUnderflow => 0x88,
            PhyTxIncomplete => 0x89,
            PhyInvalidChannel => 0x8A,
            PhyInvalidPower => 0x8B,
            PhyTxBusy => 0x8C,
            PhyTxCcaFail => 0x8D,
            PhyOscillatorCheckFailed => 0x8E,
            PhyAckReceived => 0x8F,
            NetworkUp => 0x90,
            NetworkDown => 0x91,
            JoinFailed => 0x94,
            MoveFailed => 0x96,
            CannotJoinAsRouter => 0x98,
            NodeIdChanged => 0x99,
            PanIdChanged => 0x9A,
            NetworkOpened => 0x9C,
            NetworkClosed => 0x9D,
            NotJoined => 0x93,
            InvalidSecurityLevel => 0x95,
            NetworkBusy => 0xA1,
            InvalidEndpoint => 0xA3,
            BindingHasChanged => 0xA4,
            InsufficientRandomData => 0xA5,
            ApsEncryptionError => 0xA6,
            SecurityStateNotSet => 0xA8,
            SourceRouteFailure => 0xA9,
            ManyToOneRouteFailure => 0xAA,
            NoBeacons => 0xAB,
            ReceivedKeyInTheClear => 0xAC,
            NoNetworkKeyReceived => 0xAD,
            NoLinkKeyReceived => 0xAE,
            PreconfiguredKeyRequired => 0xAF,
            StackAndHardwareMismatch => 0xB0,
            IndexOutOfRange => 0xB1,
            KeyTableInvalidAddress => 0xB3,
            TableFull => 0xB4,
            LibraryNotPresent => 0xB5,
            TableEntryErased => 0xB6,
            SecurityConfigurationInvalid => 0xB7,
            TooSoonForSwitchKey => 0xB8,
            OperationInProgress => 0xBA,
            KeyNotAuthorized => 0xBB,
            SecurityDataInvalid => 0xBD,
            ApplicationError0 => 0xF0,
            ApplicationError1 => 0xF1,
            ApplicationError2 => 0xF2,
            ApplicationError3 => 0xF3,
            ApplicationError4 => 0xF4,
            ApplicationError5 => 0xF5,
            ApplicationError6 => 0xF6,
            ApplicationError7 => 0xF7,
            ApplicationError8 => 0xF8,
            ApplicationError9 => 0xF9,
            ApplicationError10 => 0xFA,
            ApplicationError11 => 0xFB,
            ApplicationError12 => 0xFC,
            ApplicationError13 => 0xFD,
            ApplicationError14 => 0xFE,
            ApplicationError15 => 0xFF,
        };
        buffer.put_u8(byte);
    }
}
